import type { Pair, Product } from "@/lib/types";

/**
 * The catalog. Prices are whole RWF and are the single source of truth:
 * the order API recalculates every total from this file.
 */
export const products: readonly Product[] = [
  {
    id: "serum",
    slug: "vitamin-c-serum",
    name: "Vitamin C Serum",
    kind: "skincare",
    label: ["Vitamin C", "Serum"],
    format: "Vitamin C serum",
    size: "30 ml",
    price: 35_000,
    tagline: "A stable 15% vitamin C serum for even, luminous skin.",
    ingredients: "Vitamin C, ferulic acid, vitamin E",
    howToUse: "Apply 3 to 4 drops to clean skin each morning, before moisturizer.",
    palette: { from: "#F0B545", to: "#B9650F", ink: "#2B1604", onInk: "#FFE9C2" },
    art: { shape: "dropper", glass: "#E07A1F" },
    featured: true,
  },
  {
    id: "cream",
    slug: "barrier-repair-cream",
    name: "Barrier Repair Cream",
    kind: "skincare",
    label: ["Barrier", "Repair Cream"],
    format: "Ceramide cream",
    size: "50 ml",
    price: 28_000,
    tagline: "A rich, fragrance-free cream that restores comfort to dry, reactive skin.",
    ingredients: "Ceramides, squalane, panthenol",
    howToUse: "Apply morning and night as the last step of your routine.",
    palette: { from: "#86A58A", to: "#2F4B3A", ink: "#FFFFFF", onInk: "#2F4B3A" },
    art: { shape: "jar" },
    featured: true,
  },
  {
    id: "essence",
    slug: "hyaluronic-essence",
    name: "Hyaluronic Essence",
    kind: "skincare",
    label: ["Hyaluronic", "Essence"],
    format: "Hyaluronic essence",
    size: "100 ml",
    price: 24_000,
    tagline: "A weightless essence layering three weights of hyaluronic acid.",
    ingredients: "Hyaluronic acid, panthenol, aloe",
    howToUse: "Press two pumps into damp skin, then moisturize.",
    palette: { from: "#4C74D9", to: "#1A2C6E", ink: "#FFFFFF", onInk: "#1A2C6E" },
    art: { shape: "pump", glass: "#1E3F9E" },
    featured: true,
  },
  {
    id: "spf",
    slug: "sunscreen-spf-50",
    name: "Sunscreen SPF 50",
    kind: "skincare",
    label: ["SPF 50", "Sunscreen"],
    format: "Mineral sunscreen",
    size: "50 ml",
    price: 18_000,
    tagline: "Broad-spectrum SPF 50 that disappears on every skin tone, with no white cast.",
    ingredients: "Zinc oxide, niacinamide, vitamin E",
    howToUse: "Apply generously as the last morning step. Reapply every 2 hours in the sun.",
    palette: { from: "#F4A27E", to: "#B1462B", ink: "#2E1108", onInk: "#FFE6D9" },
    art: { shape: "tube", tube: "#F7F1EA" },
    featured: true,
  },
  {
    id: "niacin",
    slug: "niacinamide-serum",
    name: "Niacinamide Serum",
    kind: "skincare",
    label: ["Niacinamide", "10% Serum"],
    format: "Niacinamide + zinc serum",
    size: "30 ml",
    price: 22_000,
    tagline: "A clarifying serum that fades dark spots and evens out skin tone.",
    ingredients: "Niacinamide 10%, zinc PCA, tranexamic acid",
    howToUse: "Apply 3 drops morning and night after cleansing.",
    palette: { from: "#D9A38F", to: "#7A3E34", ink: "#2C130E", onInk: "#FBE7DF" },
    art: { shape: "dropper", glass: "#B5654F" },
  },
  {
    id: "cleanser",
    slug: "gentle-cleanser",
    name: "Gentle Cleanser",
    kind: "skincare",
    label: ["Gentle", "Cleanser"],
    format: "Low-foam gel cleanser",
    size: "150 ml",
    price: 14_000,
    tagline: "A soft gel cleanser that lifts away dust and sunscreen without tightness.",
    ingredients: "Glycerin, oat extract, panthenol",
    howToUse: "Massage one pump onto damp skin morning and night, then rinse.",
    palette: { from: "#A7A9B8", to: "#3E4157", ink: "#FFFFFF", onInk: "#3E4157" },
    art: { shape: "pump", glass: "#5A5F80" },
  },
  {
    id: "shea",
    slug: "shea-body-butter",
    name: "Shea Body Butter",
    kind: "skincare",
    label: ["Shea", "Body Butter"],
    format: "Whipped body butter",
    size: "200 ml",
    price: 16_000,
    tagline: "Rich, whipped shea butter that keeps skin soft from head to toe.",
    ingredients: "Shea butter, coconut oil, vitamin E",
    howToUse: "Warm a little between your palms and smooth over skin after a shower.",
    palette: { from: "#D6B48A", to: "#7A5532", ink: "#2A1A0B", onInk: "#F8EBD8" },
    art: { shape: "jar", cream: "#F3E2C0" },
  },
  {
    id: "collagen",
    slug: "collagen-vitamin-c",
    name: "Collagen + Vitamin C",
    kind: "vitamin",
    label: ["Collagen", "+ Vitamin C"],
    format: "Capsules",
    size: "60 capsules",
    price: 30_000,
    tagline: "Marine collagen peptides with vitamin C, in a once-daily serving.",
    ingredients: "Collagen peptides, vitamin C, hyaluronic acid",
    howToUse: "Take two capsules daily with water and food.",
    palette: { from: "#C24A6B", to: "#5A1330", ink: "#FFFFFF", onInk: "#5A1330" },
    art: { shape: "capsules", capsule: ["#C24A6B", "#F6E9DC"] },
    featured: true,
  },
  {
    id: "omega",
    slug: "omega-3-softgels",
    name: "Omega-3 Softgels",
    kind: "vitamin",
    label: ["Omega-3", "Softgels"],
    format: "Algae-based softgels",
    size: "60 softgels",
    price: 22_000,
    tagline: "Plant-based EPA and DHA to support skin comfort and suppleness.",
    ingredients: "Algae oil (EPA, DHA), vitamin E",
    howToUse: "Take two softgels daily with a meal.",
    palette: { from: "#2A9AA0", to: "#0A3B44", ink: "#FFFFFF", onInk: "#0A3B44" },
    art: { shape: "softgels" },
    featured: true,
  },
  {
    id: "biotin",
    slug: "biotin-zinc",
    name: "Biotin + Zinc",
    kind: "vitamin",
    label: ["Biotin", "+ Zinc"],
    format: "Vegan capsules",
    size: "60 capsules",
    price: 15_000,
    tagline: "Biotin and zinc, which support normal skin, hair and nails.",
    ingredients: "Biotin, zinc bisglycinate",
    howToUse: "Take one capsule daily with water.",
    palette: { from: "#8466D8", to: "#2E1B66", ink: "#FFFFFF", onInk: "#2E1B66" },
    art: { shape: "capsules", capsule: ["#8466D8", "#F6E9DC"] },
    featured: true,
  },
  {
    id: "multi",
    slug: "daily-multivitamin",
    name: "Daily Multivitamin",
    kind: "vitamin",
    label: ["Daily", "Multivitamin"],
    format: "Capsules",
    size: "60 capsules",
    price: 20_000,
    tagline: "Thirteen vitamins and minerals in one daily capsule, to fill the gaps in a busy week.",
    ingredients: "Vitamins A, B, C, D, E, zinc, selenium",
    howToUse: "Take one capsule daily with breakfast.",
    palette: { from: "#6FA35A", to: "#264A1C", ink: "#FFFFFF", onInk: "#264A1C" },
    art: { shape: "capsules", capsule: ["#6FA35A", "#F6E9DC"] },
  },
  {
    id: "iron",
    slug: "iron-folate",
    name: "Iron + Folate",
    kind: "vitamin",
    label: ["Iron", "+ Folate"],
    format: "Gentle iron capsules",
    size: "60 capsules",
    price: 12_000,
    tagline: "A gentle, easy-on-the-stomach iron with folate and vitamin C.",
    ingredients: "Iron bisglycinate, folate, vitamin C",
    howToUse: "Take one capsule daily with food. Keep out of reach of children.",
    palette: { from: "#B8433A", to: "#4E1612", ink: "#FFFFFF", onInk: "#4E1612" },
    art: { shape: "capsules", capsule: ["#B8433A", "#F6E9DC"] },
  },
  {
    id: "d3",
    slug: "vitamin-d3-k2",
    name: "Vitamin D3 + K2",
    kind: "vitamin",
    label: ["Vitamin D3", "+ K2"],
    format: "Softgels",
    size: "60 softgels",
    price: 14_000,
    tagline: "Vitamin D3 with K2, which support normal bones and immune function.",
    ingredients: "Vitamin D3 (cholecalciferol), vitamin K2 (MK-7), olive oil",
    howToUse: "Take one softgel daily with a meal.",
    palette: { from: "#E8C547", to: "#8A6A0E", ink: "#2A2205", onInk: "#FFF3C4" },
    art: { shape: "softgels" },
  },
];

export const pairs: readonly Pair[] = [
  {
    id: "serum-collagen",
    products: ["serum", "collagen"],
    title: "Brighten, inside and out",
    text: "Vitamin C works on the surface of your skin. Collagen peptides with vitamin C give your body the building blocks from within.",
  },
  {
    id: "cream-omega",
    products: ["cream", "omega"],
    title: "Comfort for dry skin",
    text: "Ceramides rebuild the surface barrier while omega-3s support skin suppleness from the inside.",
  },
  {
    id: "essence-biotin",
    products: ["essence", "biotin"],
    title: "Hydrate and fortify",
    text: "Hyaluronic acid draws water into the skin. Biotin and zinc support the skin, hair and nails a cream can't reach.",
  },
  {
    id: "spf-d3",
    products: ["spf", "d3"],
    title: "Sun-ready",
    text: "Sunscreen shields your skin from UV every day. Vitamin D3 with K2 keeps up the vitamin you'd otherwise get from the sun.",
  },
  {
    id: "niacin-multi",
    products: ["niacin", "multi"],
    title: "Even tone, every day",
    text: "Niacinamide fades dark spots on the surface while a daily multivitamin covers the nutrients your skin draws on.",
  },
];

const byId = new Map(products.map((p) => [p.id, p]));
const bySlug = new Map(products.map((p) => [p.slug, p]));

export const getProduct = (id: string): Product | undefined => byId.get(id);
export const getProductBySlug = (slug: string): Product | undefined => bySlug.get(slug);
export const featuredProducts = (): readonly Product[] => {
  const featured = products.filter((p) => p.featured);
  return featured.length ? featured : products;
};
export const pairFor = (productId: string): Pair | undefined =>
  pairs.find((pr) => pr.products.includes(productId));

